### ISSUE TITLE
Remove Server Selection Page

### ISSUE THREAD

**Issue by fbaig** [I-GUIDE/CI_Platform#30]
Can we remove the Server selection page? I don't think it is useful anymore and as of now just adding an additional step for the user and can possibly confuse new users as well.
<img width="1512" alt="Screenshot 2024-07-09 at 10 07 45 AM" src="https://github.com/I-GUIDE/CI_Platform/assets/11427468/b871d534-35c2-46e1-97df-9603dcbae49e">

**Comment by rkalyanapurdue** [comment]
This has been fixed; server selection page will no longer show up.
