### ISSUE TITLE
Create a detailed system diagram

### ISSUE THREAD

**Issue by rkalyanapurdue** [I-GUIDE/CI_Platform#8]
1. Need a detailed system diagram that can be used by all team members to get an idea of how everything is deployed and integrated.
2. The system diagram should eventually be part of documentation developed for I-GUIDE's CI platform.
3. Create a Read The Docs page for the CI platform.

**Comment by fbaig** [comment]
![iguide-platfrom-design-2](https://github.com/I-GUIDE/CI_Platform/assets/11427468/9feb847c-9c96-43fe-b101-80e5f5bbc8ae)


[Editable version of the system diagram](https://docs.google.com/drawings/d/1mohXAxyegmVvR0VBGVF-wPEjv_ExbkACno_DqPaIKNE/edit)
