### ISSUE TITLE
GitHub Pages Documentation for the platform

### ISSUE THREAD

**Issue by fbaig** [I-GUIDE/CI_Platform#9]
Create GitHub pages to keep track of documentation for the CI_Platform (`documentation` branch attached)

**Comment by rkalyanapurdue** [comment]
Add the new system diagram to the docs

**Comment by fbaig** [comment]
1. Create a separate repository for documentation.
2. Release notes go into Wiki page

**Comment by fbaig** [comment]
- [x] GitHub pages documentation is created https://github.com/I-GUIDE/i-guide.github.io. All future external documentation related work should be opened as new issues in https://github.com/I-GUIDE/i-guide.github.io. `documentation` branch in this repository has been moved and deleted.
- [x] Wiki pages are created and active at https://github.com/I-GUIDE/CI_Platform/wiki. Previous Release Notes are copied into the Wiki. Future Release Notes should go into the Wiki
